name: irl
channels:
  - pytorch
  - defaults
dependencies:
    - python=3.8.*
    - pip=21.0.*
    - pytorch=1.10.2
    - cpuonly
    - pip:
        - numpy
        - pandas
        - matplotlib
        - sklearn
        - stable-baselines3